---
kind: ReplicationController
apiVersion: v1
metadata:
  name: crossbar-controller
  labels:
    name: crossbar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: crossbar
    spec:
      containers:
      - name: crossbar
        image: 10.67.20.19:5000/crossbar
        ports:
        - name: ws
          containerPort: 8080
