---
kind: Service
apiVersion: v1
metadata:
  name: emqttd
spec:
  ports:
  - port: 1883
    targetPort: mqtt
    nodePort: 30003
    name: mqtt
  - port: 18083
    targetPort: dashboard
    nodePort: 30004
    name: dashboard
  selector:
    name: emqttd
  type: NodePort
  externalIPs:
    - 147.162.226.101