---
kind: Service
apiVersion: v1
metadata:
  name: meteor
spec:
  ports:
  - port: 80
    targetPort: http-server
    nodePort: 30003
  selector:
    name: meteor
  sessionAffinity: ClientIP
  type: NodePort
  externalIPs:
    - 147.162.226.101