apiVersion: v1
kind: ReplicationController
metadata:
  name: ms-example-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-example
    spec:
      containers:
      - name: ms-example
        image: 10.67.20.19:5000/ms-example
        ports:
        - containerPort: 8080
