apiVersion: v1
kind: ReplicationController
metadata:
  name: autobahnsample-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: autobahnsample
    spec:
      containers:
      - name: ms-example
        image: asimioni/autobahnsample
        ports:
        - containerPort: 8080
