---
kind: ReplicationController
apiVersion: v1
metadata:
  name: metrics-exporter
  labels:
    name: metrics-exporter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: metrics-exporter
    spec:
      containers:
      - name: metrics-exporter
        image: 10.67.20.19:5000/metrics-exporter
        ports:
        - name: http-server
          containerPort: 8080
  
