apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics-exporter
spec:
  template:
    metadata:
      labels:
        app: metrics-exporter
    spec:
      containers:
      - name: metrics-exporter
        image: asimioni/metrics-exporter
        resources:
          requests:
            cpu: "500m"
          limits:
            cpu: "1000m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-exporter
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: metrics-exporter
