---
kind: ReplicationController
apiVersion: v1
metadata:
  name: data-stream-generator-controller
  labels:
    name: data-stream-generator
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: data-stream-generator
    spec:
      containers:
      - name: oplog-admin
        image: 10.67.20.19:5000/data-stream-generator
        ports:
        - name: http-server
          containerPort: 8080
        - name: zeromq
          containerPort: 3000