---
kind: Service
apiVersion: v1
metadata:
  name: data-stream-configuration-interface
spec:
  ports:
  - port: 8080
    targetPort: http-server
    name: http
  selector:
    name: data-stream-generator
---

kind: Service
apiVersion: v1
metadata:
  name: data-stream-generator
spec:
  ports:
  - port: 3000
    targetPort: zeromq
    name: zeromq
  selector:
    name: data-stream-generator
  sessionAffinity: ClientIP