apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-web-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-web-app
    spec:
      containers:
      - name: node-web-app
        image: 10.67.20.19:5000/node-web-app
        ports:
        - containerPort: 8080
